//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveNetworkDocumentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhadamatMashiniPersonnel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> SematId { get; set; }
        public string TelDakheli { get; set; }
        public string TelMostaghim { get; set; }
        public string Mobile { get; set; }
        public Nullable<byte> ManateghId { get; set; }
    
        public virtual Manategh Manategh { get; set; }
        public virtual Semat Semat { get; set; }
    }
}
