//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveNetworkDocumentation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiveNetworkDocumentationEntities : DbContext
    {
        public LiveNetworkDocumentationEntities()
            : base("name=LiveNetworkDocumentationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KhadamatMashiniPersonnel> KhadamatMashiniPersonnels { get; set; }
        public virtual DbSet<Manategh> Manateghs { get; set; }
        public virtual DbSet<Semat> Semats { get; set; }
        public virtual DbSet<VoipLine> VoipLines { get; set; }
    }
}
