//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveNetworkDocumentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoipLine
    {
        public byte Id { get; set; }
        public string FileNumber { get; set; }
        public Nullable<int> Vlan { get; set; }
        public bool HaveVlan { get; set; }
        public string IpWanMantagheSide { get; set; }
        public bool IsPinged { get; set; }
        public Nullable<System.DateTime> DateRecievedOnFiberInSite { get; set; }
        public Nullable<System.DateTime> DateCompletelyOperated { get; set; }
        public string LetterNumber { get; set; }
        public string LetterId { get; set; }
        public byte ManateghId { get; set; }
    
        public virtual Manategh Manategh { get; set; }
    }
}
